---
- name: Playbook to manage DNS forward zone
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  # Ensure DNS zone is present
  - freeipa.ansible_freeipa.ipadnsforwardzone:
      ipaadmin_password: SomeADMINpassword
      state: absent
