---
- name: Playbook to handle sudocmdgroups
  hosts: ipaserver
  become: true

  tasks:
  # Ensure sudo commands are present
  - freeipa.ansible_freeipa.ipasudocmd:
     ipaadmin_password: SomeADMINpassword
     name:
     - /usr/sbin/ifconfig
     - /usr/sbin/iwlist
     state: present

  # Ensure sudo commands are present in existing sudocmdgroup
  - freeipa.ansible_freeipa.ipasudocmdgroup:
     ipaadmin_password: SomeADMINpassword
     name: network
     sudocmd:
     - /usr/sbin/ifconfig
     - /usr/sbin/iwlist
     action: member
