---
- name: Playbook to configure IPA server step1
  hosts: ipaserver
  become: true

  collections:
    - freeipa.ansible_freeipa

  tasks:
  - name: import role from a collection
    import_role:
      name: ipaserver    
