---
collections:
  # Install a collection from Ansible Galaxy.
  - name: freeipa.ansible_freeipa
#    version: >=0.3.4, <0.5.0
#roles:
  # Installing role from Ansible_Galaxy.
 # - name: community.general.ipa_host