---
- name: Host member managedby_host present
  hosts: ipaserver
  become: true

  tasks:
  - freeipa.ansible_freeipa.ipahost:
      ipaadmin_password: SomeADMINpassword
      name: host01.exmaple.com
      managedby_host: server.exmaple.com
      action: member
