---
- name: Test DNS Record is present.
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  # Ensure that dns record is present
  - freeipa.ansible_freeipa.ipadnsrecord:
      ipaadmin_password: SomeADMINpassword
      name: host01
      zone_name: example.com
      record_type: 'AAAA'
      record_value: '::1'
      state: present
