---
- name: Test TXT Record is present.
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  # Ensure a TXT record is absent
  - freeipa.ansible_freeipa.ipadnsrecord:
      ipaadmin_password: SomeADMINpassword
      name: _kerberos
      record_type: 'TXT'
      record_value: 'EXAMPLE.COM'
      zone_name: example.com
      state: present
