---
- name: Playbook to manage IPA service.
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  # Ensure management host is present.
  - freeipa.ansible_freeipa.ipaservice:
      ipaadmin_password: SomeADMINpassword
      name: HTTP/www.example.com
      host: "{{ groups.ipaserver[0] }}"
      action: member
