---
- name: Tests
  hosts: ipaserver
  become: true

  tasks:
  # Ensure sudorule command is absent
  - freeipa.ansible_freeipa.ipasudorule:
      ipaadmin_password: pass1234
      name: testrule1
      state: absent
