---
- name: Playbook to handle users
  hosts: ipaserver
  become: true

  tasks:
  - name: Remove user pinky and brain
    freeipa.ansible_freeipa.ipauser:
      ipaadmin_password: SomeADMINpassword
      name: pinky
      state: absent
