---
- name: Tests
  hosts: ipaserver
  become: no
  gather_facts: no

  tasks:
    - name: Retrieve data from symmetric vault.
      freeipa.ansible_freeipa.ipavault:
        ipaadmin_password: SomeADMINpassword
        name: symvault
        username: admin
        password: SomeVAULTpassword
        state: retrieved
      register: result
      no_log: true
    - debug:
        msg: "{{ result.vault.data }}"
